ekyna_setting_admin_show:
    path: /admin/settings/show
    defaults: 
        _controller: "ekyna_setting.controller:showAction"
    requirements:
        _method: GET

ekyna_setting_admin_edit:
    path: /admin/settings/edit
    defaults: 
        _controller: "ekyna_setting.controller:editAction"
    requirements:
        _method: GET|POST