ekyna_setting_parameter_admin_show:
    path: /show
    defaults:
        _controller: "ekyna_setting.parameter.controller:showAction"
    methods: [GET]

ekyna_setting_parameter_admin_edit:
    path: /edit
    defaults:
        _controller: "ekyna_setting.parameter.controller:editAction"
    methods: [GET|POST]
