ekyna_setting_redirection_admin_home:
    path: ""
    defaults: { _controller: "ekyna_setting.redirection.controller:homeAction" }
    methods: [GET]

ekyna_setting_redirection_admin_list:
    path: /list
    defaults: { _controller: "ekyna_setting.redirection.controller:listAction" }
    methods: [GET|POST]

ekyna_setting_redirection_admin_new:
    path: /new
    defaults: { _controller: "ekyna_setting.redirection.controller:newAction" }
    methods: [GET|POST]

ekyna_setting_redirection_admin_show:
    path: /{redirectionId}/show
    defaults: { _controller: "ekyna_setting.redirection.controller:showAction" }
    methods: [GET]
    requirements:
        redirectionId: \d+

ekyna_setting_redirection_admin_edit:
    path: /{redirectionId}/edit
    defaults: { _controller: "ekyna_setting.redirection.controller:editAction" }
    methods: [GET|POST]
    requirements:
        redirectionId: \d+

ekyna_setting_redirection_admin_toggle:
    path: /{redirectionId}/toggle/{field}
    defaults: { _controller: "ekyna_setting.redirection.controller:toggleAction", field: "enabled" }
    methods: [GET]
    requirements:
        redirectionId: \d+
        field: \w+

ekyna_setting_redirection_admin_remove:
    path: /{redirectionId}/remove
    defaults: { _controller: "ekyna_setting.redirection.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        redirectionId: \d+
