ekyna_setting_redirection_admin:
    resource: "admin/redirection.yml"
    prefix:   /redirection

ekyna_setting_helper_admin:
    resource: "admin/helper.yml"
    prefix:   /helper

ekyna_setting_parameter_admin:
    resource: "admin/parameter.yml"
    prefix:   /parameter

